version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  backend:
    build: .
    restart: always
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - app_network

  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    expose:
      - "3000"
    networks:
      - app_network

  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web_app/static/:/app/static/
      - ./certs/spotnet.xyz.chain.crt:/etc/nginx/spotnet.xyz.chain.crt:ro
      - ./certs/spotnet.xyz.key:/etc/nginx/spotnet.xyz.key:ro
      - ./spotnet.conf:/etc/nginx/conf.d/spotnet.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app_network