version: '3.8'

services:
  backend_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_dev
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=test_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      # Add other environment variables your app needs
    depends_on:
      - db
    command: >
      sh -c "pip install -r requirements.txt &&
             python -m pytest integration_tests/ -v --cov=web_app"

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: