name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Create .env file
        run: cp .env.dev .env

      - name: Build and deploy
        run: |
          # Build and start containers for production
          docker compose -f docker-compose.yaml up -d --build
          
          # Verify backend is running
          docker compose ps backend
          
          

      - name: Verify deployment
        run: |
          # Check if all services are running
          if ! docker compose ps --services --filter "status=running" | grep -q .; then
            echo "Deployment verification failed - containers are not running"
            exit 1
          fi
          
          # Wait for backend to be ready (adjust URL as needed)
          timeout 60s bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8000/health)" != "200" ]]; do sleep 5; done'

      - name: Cleanup
        if: always()
        run: |
          # Remove unused images
          docker image prune -f
          
          # Optional: Remove old backups
          find . -name "*.bak" -type f -mtime +7 -delete

      - name: Rollback on failure
        if: failure()
        run: |
          # Stop current deployment
          docker compose down
          
          # Restore from previous state if available
          if [ -f "docker-compose.prev.yaml" ]; then
            docker compose -f docker-compose.prev.yaml up -d
          fi