name: CD Pipeline

on:
    workflow_run:
        workflows:
            - CI Workflow
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Prepare environment file
              run: cp .env.dev .env

            - name: Build and Deploy with Docker Compose
              run: |
                  # Ensure Docker Compose is installed
                  sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                  sudo chmod +x /usr/local/bin/docker-compose

                  # Navigate to the deployment directory
                  mkdir -p ~/app
                  cp docker-compose.yml ~/app/
                  cp .env ~/app/

                  cd ~/app

                  # Backup current .env if exists
                  if [ -f '.env' ]; then
                    cp .env .env.backup
                  fi

                  # Pull the latest Docker images
                  docker-compose pull

                  # Stop and remove existing containers
                  docker-compose down

                  # Start containers with the latest configuration
                  docker-compose up -d

                  # Clean up unused Docker images
                  docker image prune -f

                  # Verify deployment
                  echo 'Checking container status...'
                  docker-compose ps
