name: Integration Tests

on:
  push:
    branches:
      - main
      - feature/create-generic-workflow
  pull_request:
    branches:
      - main
      - feature/create-generic-workflow

jobs:
  integration-tests:
    uses: ./.github/workflows/test_workflow.yml
    with:
      python-version: "3.x"
      env-vars: |
        DB_PORT=5432
        DB_NAME=spotnet
        DB_USER=postgres
        DB_PASSWORD=password
        DB_HOST=db
        STARKNET_NODE_URL=http://51.195.57.196:6060/v0_7
        REDIS_HOST=redis
        REDIS_PORT=6379
        ENV_VERSION=DEV

#    steps:
#      - name: Build and Start Containers
#        run: |
#          docker compose -f docker-compose.dev.yaml up -d --build
#          echo "Waiting for containers to be ready..."
#          sleep 30
#
#      - name: Run Integration Tests with Coverage
#        run: |
#          docker compose exec backend bash -c "cd /app && python -m pytest web_app/test_integration/ -v"
