name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DB_PORT: 5432
  DB_NAME: spotnet
  DB_USER: postgres
  DB_PASSWORD: password
  DB_HOST: db
  REDIS_HOST: redis
  REDIS_PORT: 6379
  ENV_VERSION: DEV

jobs:
  integration-tests:
    uses: ./.github/workflows/workflow.yml
    with:
      python-version: "3.12"
      additional-steps: |
        [
          "docker-compose -f docker-compose.dev.yaml up -d --build",
          "docker-compose exec backend poetry run pytest web_app/test_integration/ -v",
          "docker-compose down"
        ]
    secrets:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
