name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    uses: ./.github/workflows/test_workflow.yml
    with:
      python-version: '3.12'
      package-manager: 'poetry'
      steps_override: |
        - name: Create .env file
          run: |
            cat << EOF > .env
            DB_USER=postgres
            DB_PASSWORD=password
            ...
            EOF
        - name: Run Integration Tests
          run: |
            docker-compose exec backend pytest tests/integration/
