name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DB_PORT: 5432
  DB_NAME: spotnet
  DB_USER: postgres
  DB_PASSWORD: password
  DB_HOST: db
  STARKNET_NODE_URL: http://51.195.57.196:6060/v0_7
  REDIS_HOST: redis
  REDIS_PORT: 6379
  ENV_VERSION: DEV

jobs:
  call_generic_workflows:
    uses: ./.github/workflows/workflow.yml
    with:
      matrix:
        python-version: ["3.12"]

