name: Pylint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/shared_workflow.yml
    with:
      python-version: "3.12"

  another_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') --disable=all --enable=C0114,C0115,C0116,C0301
