name: Pylint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call_generic_workflows:
    uses: ./.github/workflows/workflow.yml@feature/create-generic-workflow
    with:
      matrix:
        python-version: ["3.12"]