name: Pylint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pylint:
    uses: ./.github/workflows/test_workflow.yml
    with:
      python-version: '3.12'
      package-manager: 'poetry'
      steps_override: |
        - name: Install pylint
          run: pip install pylint
        - name: Run pylint
          run: pylint $(git ls-files '*.py') --disable=all --enable=C0114,C0115,C0116,C0301
