name: Pylint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/workflow.yml
    with:
      matrix:
        python-version: ["3.12"]