name: Pylint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call_generic_workflows:
    uses: ./spotnet/.github/workflows/workflow.yml
    with:
      matrix:
        python-version: ["3.12"]