name: Pylint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pylint:
    uses: ./.github/workflows/workflow.yml
    with:
      python-version: "3.12"
      additional-steps: |
        [
          "pylint $(git ls-files '*.py') --disable=all --enable=C0114,C0115,C0116,C0301"
        ]
